FIRST_WARMUP_DURATION =  40.0
WARMUP_DURATION =  20.0
PRE_ROUND_DURATION = 4.0
ROUND_DURATION = 60.0
PICKUPS_CREATION_TIME = 20.0
ABILITY_POINTS = 2
GEM_SPAWN_TIME = 10.0
GEM_RESPAWN_TIME = 15.0
ROUNDS_TO_WIN = 5
ROUNDS_DIFFERENCE_TO_WIN = 3

if IsInToolsMode() then
    --FIRST_WARMUP_DURATION =  5.0
    --WARMUP_DURATION = 5.0
    --PRE_ROUND_DURATION = 0.0
    ROUND_DURATION = 5.0
    PICKUPS_CREATION_TIME = 2.0
    GEM_SPAWN_TIME = 5.0
    GEM_RESPAWN_TIME = 5.0
end