ROUND_DURATION = 60.0
WARMUP_DURATION =  15.0
PICKUPS_CREATION_TIME = 20.0
ABILITY_POINTS = 2

if IsInToolsMode() then
    ROUND_DURATION = 1
    WARMUP_DURATION = 1
    PICKUPS_CREATION_TIME = 2.0
end